### ISSUE TITLE
Request to add .env.example file

### ISSUE THREAD

**Issue by Andryrasolofomanana** [kamounation/owl#16]
Hi there! I would like to request that a .env.example file be added to the repository. This file would serve as a template for the .env file and would contain placeholders for sensitive information such as API keys and passwords. By providing this template, we can ensure that all developers working on the project have a clear understanding of the environment variables that need to be set up in order to run the application locally.

Thanks for considering this request!

**Comment by Xlaez** [comment]
approved!
